=head1 Mapping Pod to Pandoc document model

=head2 Formatting codes

Formatting codes for I<italic text>, B<bold text>, and C<code> are mapped to
Emphasized text (C<Emph>), strongly emphasized text (C<Strong>), and inline
code (C<Code>). Formatting code for F<filenames> are mapped to inline code with
class C<filename>.

Formatting codes inside code and filenames (e.g. C<code with B<bold>> or
F<L<http://example.org/>> as filename) are ignored.

=head2 Links

Links

L<http://example.org/>

L<perl(5)>

L<crontab(5)/"ENVIRONMENT">

L<hell itself!|crontab(5)>

L<pandoc-walk>

Link text can contain formatting codes:

L<a I<helpful> script|perldoc-walk>


L</"Member Data">

L<the various attributes|/"Member Data">

L<perlsyn/"Basic BLOCKs and Switch Statements">

L<SWITCH statements|perlsyn/"Basic BLOCKs and Switch Statements">

=head3 Titles B<may contain formatting codes>!

=head2 Lists

=over

=item 1

Numbered lists are

=item 2

converted to C<NumberedList> and

=over

=item *

Bulleted lists are

=item *

converted to

C<BulletList>

=back

=back

=over

=item Foo

=item Bar

=item Doz

Some I<definition>.

=back

=head2 over/back

=over

An C<=over>...C<=back> region containing no C<=item> is mapped to C<BlockQuote>.

=back

=head2 verbatim section

  verbatim sections are mapped 
    to code blocks
    
=cut
